# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: King D The MC
email: kingdthemc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I'm only here so I don't get fined
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kingdthemc.com" # the base hostname & protocol for your site, e.g. http://example.com

author: Dave M. Coats

#share:
#twitter: true
#gplus: true
#


# Google Analytics
google_analytics: UA-128038081-1



social:
twitter_username: kingdthemc
instagram: kingdthemc
#stackoverflow: kingdthemc
#tumblr: kingdthemc
#github_username:  KingDTheMC
#rss: feed.xml

timezone: America/Los_Angeles


# Build settings
markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - .gitignore
    - CNAME

#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
